import { useMemo, useState } from 'react'
import { Activity, ArrowUpRight, Bot, Check, CheckCircle2, Clock3, MessageSquareText, Plus, Radio, Sparkles, Users, X } from 'lucide-react'
import { AuthOverlay, useAuthProfileReady, useMutations, usePresenceRoom, useQuery, useUser } from 'deepspace'
import { ChatPanel } from '../../components/ChatPanel'
import { APP_NAME } from '../../constants'

type Room = { title: string; slug: string; status: string; ownerId: string }
type Decision = { roomId: string; title: string; context: string; owner: string; status: string; priority: string; createdBy: string }
type RecordRow<T> = { recordId: string; data: T; createdAt: string }
const starterDecisions: Array<Omit<Decision, 'roomId' | 'createdBy'>> = [
  { title: 'Freeze the API contract', context: 'The mobile client is 80% through migration. Lock the response shape before QA starts.', owner: 'Maya Chen', status: 'open', priority: 'high' },
  { title: 'Use the dark launch cohort', context: 'Start with 10% of traffic so we can watch error rate and support volume together.', owner: 'Jordan Lee', status: 'open', priority: 'medium' },
  { title: 'Move the retro to Friday', context: 'Give the team one quiet day after the cutover to capture useful signals.', owner: 'Alex Rivera', status: 'decided', priority: 'low' },
]
function initials(name: string) { return name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() }
function timeAgo(value: string) { const minutes = Math.max(1, Math.round((Date.now() - Date.parse(value)) / 60000)); return minutes < 60 ? `${minutes}m ago` : `${Math.round(minutes / 60)}h ago` }

export default function HomePage() {
  const { isSignedIn, user } = useAuthProfileReady({ requireUser: true })
  const { user: currentUser } = useUser()
  const [showAuth, setShowAuth] = useState(false)
  const [showNew, setShowNew] = useState(false)
  const [newTitle, setNewTitle] = useState('')
  const [activeRoomId, setActiveRoomId] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const { records: rooms } = useQuery<Room>('rooms', { orderBy: 'createdAt', orderDir: 'desc' })
  const { create: createRoom } = useMutations<Room>('rooms')
  const { records: allDecisions } = useQuery<Decision>('decisions', { orderBy: 'createdAt', orderDir: 'desc', limit: 100 })
  const { create: createDecision, put: updateDecision } = useMutations<Decision>('decisions')
  const room = activeRoomId ? rooms.find((item) => item.recordId === activeRoomId) : rooms[0]
  const decisions = useMemo(() => allDecisions.filter((item) => item.data.roomId === room?.recordId), [allDecisions, room?.recordId])
  const { peers, connected } = usePresenceRoom(`room:${room?.recordId ?? 'lobby'}`)

  const seedRoom = async () => {
    if (!currentUser || rooms.length > 0) return
    const roomId = await createRoom({ title: 'Q4 mobile launch', slug: 'q4-mobile-launch', status: 'live', ownerId: currentUser.id })
    for (const decision of starterDecisions) await createDecision({ ...decision, roomId, createdBy: currentUser.id })
    setActiveRoomId(roomId)
  }
  const handleCreateRoom = async () => {
    const title = newTitle.trim()
    if (!title || !currentUser) return
    const roomId = await createRoom({ title, slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-'), status: 'live', ownerId: currentUser.id })
    await createDecision({ roomId, createdBy: currentUser.id, title: 'What needs a decision first?', context: 'Add the first open question for this room.', owner: currentUser.name ?? 'You', status: 'open', priority: 'medium' })
    setNewTitle(''); setShowNew(false); setActiveRoomId(roomId)
  }
  const handleSeed = () => { if (!isSignedIn) setShowAuth(true); else void seedRoom() }
  const toggleDecision = async (item: RecordRow<Decision>) => { await updateDecision(item.recordId, { status: item.data.status === 'decided' ? 'open' : 'decided' }) }
  const invite = async () => { await navigator.clipboard?.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }

  return <div className="min-h-full bg-background">
    <header className="border-b border-border/70 bg-background/80 px-5 py-4 backdrop-blur md:px-8"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-[0_0_24px_rgba(233,185,73,0.2)]"><Radio className="h-4 w-4" /></div><div><div className="text-sm font-semibold tracking-tight">{APP_NAME}</div><div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">Coordination, in signal</div></div></div><div className="flex items-center gap-2"><button onClick={invite} className="hidden items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-medium text-muted-foreground transition hover:bg-muted hover:text-foreground sm:flex"><Users className="h-3.5 w-3.5" />{copied ? 'Link copied' : 'Invite team'}</button>{!isSignedIn && <button onClick={() => setShowAuth(true)} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">Sign in to edit</button>}</div></div></header>
    <main className="mx-auto max-w-[1500px] px-5 py-8 md:px-8"><div className="mb-8 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-medium uppercase tracking-[0.18em] text-primary"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-primary" />Live room</div><h1 className="max-w-3xl text-3xl font-semibold tracking-[-0.04em] text-foreground md:text-5xl">Make the next move <span className="text-muted-foreground">obvious.</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">A shared room for the decisions that keep a launch moving. Everyone sees the same signal, in real time.</p></div><div className="flex items-center gap-2"><button onClick={() => isSignedIn ? setShowNew(true) : setShowAuth(true)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-[0_8px_24px_rgba(233,185,73,0.14)] transition hover:-translate-y-0.5"><Plus className="h-4 w-4" />New room</button><button onClick={handleSeed} className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-medium text-muted-foreground transition hover:bg-muted hover:text-foreground">{rooms.length ? 'Room ready' : 'Load demo room'} <ArrowUpRight className="h-4 w-4" /></button></div></div>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="min-w-0 space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[{ label: 'Open decisions', value: decisions.filter((d) => d.data.status === 'open').length, icon: Clock3 }, { label: 'People here', value: peers.length + 1, icon: Users }, { label: 'Room health', value: connected ? 'Good' : 'Syncing', icon: Activity }].map(({ label, value, icon: Icon }) => <div key={label} className="rounded-xl border border-border bg-card/70 p-4"><div className="mb-4 flex items-center justify-between"><span className="text-xs text-muted-foreground">{label}</span><Icon className="h-4 w-4 text-primary" /></div><div className="text-2xl font-semibold tracking-tight">{value}</div></div>)}</div>
        <div className="overflow-hidden rounded-2xl border border-border bg-card/60"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4"><div><div className="flex items-center gap-2 text-sm font-semibold">{room?.data.title ?? 'Your first room'} {room && <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-primary">{room.data.status}</span>}</div><div className="mt-1 text-xs text-muted-foreground">{room ? 'Live decision queue · updates sync instantly' : 'Create a room or load the demo to get started'}</div></div><div className="flex -space-x-2">{[...(peers.map((p) => ({ id: p.userId, name: p.userName }))), ...(currentUser ? [{ id: currentUser.id, name: currentUser.name ?? 'You' }] : [])].slice(0, 4).map((person) => <div key={person.id} title={person.name} className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-card bg-accent text-[10px] font-semibold text-foreground">{initials(person.name)}</div>)}<div className="ml-3 flex items-center gap-1.5 pl-2 text-[11px] text-muted-foreground"><span className={`h-1.5 w-1.5 rounded-full ${connected ? 'bg-emerald-400' : 'bg-amber-400'}`} />{connected ? 'synced' : 'connecting'}</div></div></div>
          {!room ? <div className="flex min-h-[260px] flex-col items-center justify-center px-6 text-center"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Sparkles className="h-5 w-5" /></div><h2 className="text-sm font-semibold">Start with a shared room</h2><p className="mt-2 max-w-sm text-xs leading-5 text-muted-foreground">Load the demo room to see the full flow, or sign in and create one for your team.</p></div> : <div className="divide-y divide-border/70">{decisions.map((item) => <article key={item.recordId} className="group flex gap-4 px-5 py-5 transition hover:bg-muted/30"><button onClick={() => void toggleDecision(item)} aria-label="Toggle decision" className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border transition ${item.data.status === 'decided' ? 'border-emerald-400 bg-emerald-400 text-background' : 'border-muted-foreground/50 text-transparent hover:border-primary'}`}><Check className="h-3 w-3" /></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className={`text-sm font-medium ${item.data.status === 'decided' ? 'text-muted-foreground line-through' : 'text-foreground'}`}>{item.data.title}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider ${item.data.priority === 'high' ? 'bg-red-400/10 text-red-300' : item.data.priority === 'medium' ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'}`}>{item.data.priority}</span></div><p className="mt-1.5 max-w-2xl text-xs leading-5 text-muted-foreground">{item.data.context}</p><div className="mt-3 flex flex-wrap items-center gap-3 text-[11px] text-muted-foreground"><span className="flex items-center gap-1.5"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-accent text-[9px] font-semibold text-foreground">{initials(item.data.owner)}</span>{item.data.owner}</span><span>•</span><span>{timeAgo(item.createdAt)}</span><span className="ml-auto flex items-center gap-1 text-muted-foreground/70"><MessageSquareText className="h-3.5 w-3.5" />Discuss</span></div></div></article>)}</div>}
          {room && <div className="border-t border-border px-5 py-3"><button onClick={() => isSignedIn ? setShowNew(true) : setShowAuth(true)} className="flex w-full items-center gap-2 text-xs font-medium text-muted-foreground transition hover:text-primary"><Plus className="h-4 w-4" />Add a decision to this room</button></div>}</div></section>
        <aside className="flex min-h-[520px] flex-col overflow-hidden rounded-2xl border border-border bg-card/80"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div className="flex items-center gap-2"><div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10 text-primary"><Bot className="h-4 w-4" /></div><div><div className="text-sm font-semibold">Room brief</div><div className="text-[11px] text-muted-foreground">AI copilot · synced to this room</div></div></div><Sparkles className="h-4 w-4 text-primary" /></div>{isSignedIn && user ? <ChatPanel chatId={null} userId={user.id} compact className="min-h-0 flex-1" header={<div className="border-b border-border/70 px-5 py-3 text-xs leading-5 text-muted-foreground">Ask for a summary, risk scan, or next best action.</div>} emptyStatePrompts={['Give me the room brief', 'What is blocking launch?', 'Draft the next update']} /> : <div className="flex flex-1 flex-col items-center justify-center px-6 text-center"><div className="mb-4 rounded-full border border-primary/30 bg-primary/10 p-3 text-primary"><Bot className="h-5 w-5" /></div><h2 className="text-sm font-semibold">Your copilot is ready</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Sign in to ask for a live brief grounded in the room’s synced records.</p><button onClick={() => setShowAuth(true)} className="mt-5 rounded-lg border border-border px-3 py-2 text-xs font-semibold text-foreground hover:bg-muted">Sign in</button></div>}</aside></div>
      <div className="mt-6 flex flex-wrap items-center justify-between gap-3 text-[11px] text-muted-foreground"><div className="flex items-center gap-2"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" />DeepSpace records + presence are live on this page</div><div className="flex items-center gap-3"><span>Chat is public by design</span><span>•</span><span>AI brief is private to your account</span></div></div>
    </main>
    {showAuth && <AuthOverlay onClose={() => setShowAuth(false)} />}
    {showNew && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Create a room</h2><p className="mt-1 text-xs text-muted-foreground">Give the next shared effort a clear name.</p></div><button onClick={() => setShowNew(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X className="h-4 w-4" /></button></div><input autoFocus value={newTitle} onChange={(event) => setNewTitle(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void handleCreateRoom()} placeholder="e.g. Payments launch" className="mt-6 w-full rounded-lg border border-input bg-background px-3 py-3 text-sm outline-none focus:border-primary" /><button onClick={() => void handleCreateRoom()} disabled={!newTitle.trim()} className="mt-4 w-full rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50">Create room</button></div></div>}
  </div>
}
